### ISSUE TITLE
P0 - 插件支持作用域隔离

### ISSUE THREAD

**Issue by JerryC8080** [JerryC8080/GlacierJS#8]
## 作用域冲突

我们都知道关于 ServiceWorker 的作用域有两个关键特性：

1. **默认的作用域是注册时候的 Path。**
2. **同个路径下同时间只能有一个 ServiceWorker 得到控制权。**

**作用域缩小与扩大**

关于第一个特性，例如注册 Service Worker 文件为 `/a/b/sw.js`，则 scope 默认为 `/a/b/`：

```typescript
if (navigator.serviceWorker) {
    navigator.serviceWorker.register('/a/b/sw.js').then(function (reg) {
        console.log(reg.scope);
        // scope => https://yourhost/a/b/
    });
}
```

当然我们可以在注册的的时候指定 `scope` 去向下缩小作用域，例如：

```typescript
if (navigator.serviceWorker) {
    navigator.serviceWorker.register('/a/b/sw.js', {scope: '/a/b/c/'})
        .then(function (reg) {
            console.log(reg.scope);
            // scope => https://yourhost/a/b/c/
        });
}
```

也可以通过服务器对 ServiceWorker 文件的响应设置 `Service-Worker-Allowed` 头部，去扩大作用域。

例如 Google Docs 在作用域 `https://docs.google.com/document/u/0/` 注册了一个来自于 `https://docs.google.com/document/offline/serviceworker.js` 的 ServiceWorker

![img](https://bluesun-1252625244.cos.ap-guangzhou.myqcloud.com/img/202204131004508.png)

**MPA下的 ServiceWorker 治理**

现代 Web App 项目主要有两种架构形式存在： **SPA(Single Page Application)** 和 **MPA(Multiple Page Application)**

MPA 这种架构的模式在现如今的大型 Web App 非常常见，这种 Web App 相比较于 SPA 能够承受更重的业务体量，并且利于大型 Web App 的后期维护和扩展，它往往会有多个团队去维护。

假设我们有一个 MPA 的站点：

```typescript
.
|-- app1
|   |-- app1-service-worker.js
|   `-- index.html
|-- app2
|   `-- index.html
|-- index.html
`-- root-service-worker.js
```

**app1** 和 **app2** 分别由不同的团队维护。

如果我们在根目录 `'/'` 注册了 `root-service-worker.js`，去完成一些通用的功能，例如：「日志收集」、「静态资源缓存」等。

然后 **app1** 团队利用 ServiceWorker 的能力开发了一些特定的功能需要，例如 app1 的「离线化功能」。

他们在 `app1/index.html `目录注册了 `app1-service-worker.js`。

这时候，访问 `app1/*` 下的所有页面，ServiceWorker 控制权会交给 `app1-service-worker.js`，也就是只有app1的「离线化功能」在工作，而原来的「日志收集」、「静态缓存」等功能会失效。

显然这种情况是我们不希望看到的，并且在实际的开发中发生的概率会很大。

解决这个问题有两种方案：

1. 封装「日志收集」、「静态资源缓存」功能，`app1-service-worker.js`引入并使用这些功能。
2. 把「离线化功能」整合到 `root-service-worker.js`，只允许注册该 ServiceWorker。

关于方案一，封装通用功能这是正确的，但是主域下的功能可能完全没办法一一拆解，并且后续主域的 ServiceWorker 更新了新功能，子域下的 ServiceWorker 还需要主动去更新和升级。

关于方案二，显然可以解决方案一的问题，但是其他应用，例如 **app2** 可能不需要「离线化功能」。

**基于此，我们引入方案三：功能整合到主域，支持功能的组合按照作用域隔离。**

基于  [GlacierJS](https://jerryc8080.github.io/GlacierJS)  的话代码上可能会是这样的：

```typescript
const mainPlugins = [
  new Collector(); // 日志收集功能
  new AssetsCache(); // 静态资源缓存功能
];

glacier.use('/', mainPlugins)；
glacier.use('/app1', [
  ...mainPlugins,
  new Offiline(),  // 离线化功能
])；
```

# 详细设计
## 2. 增加 scope-validator 拦截器
  ```typescript
   const scopeWrapped = scopeValidator({
    scope: '/app1/:module',
    getRuntimePath: () => location.pathname,
   })((context) => {
    // ...原有插件的逻辑
   
    // 读取路径匹配参数，假如：locations.pathname = '/app1/goods'
    context.pathParams; // { module: 'goods' }
   });
   
   // 作为中间件，入队 MiddlewareQueue
   middlewareQueue.push(scopeWrapped);
   ```
## 3. getRuntimePath 的来源

1. window 线程：location.pathname
2. service-worker 线程:
    1. onInstall & onActivate:
        1. 方案一：获取 self.registration.scope ?
            1. 只局限在注册的时候指定的最高 scope，并不能指的当前资源
        2. 方案二：获取当前 [visibilitystate](https://w3c.github.io/ServiceWorker/#client-visibilitystate) === 'visible' 的 client.url ?
            1. 存在问题：多个窗口打开时，visiable 会存在多个 client 为 true
                1. foucsed 是否能解决？
        3. 方案三：这三个生命周期不做命名空间隔离，因为插件本身就是被安装的。
        - [x] 方案四：进行中间件队列隔离
            1.  `app.use(scope1, middlewares1); app.use(scope2, middlewares2)` 分别创建两个隔离的队列
            2.  事件触发的时候，获取处于 visable 的 client，通过 url 去寻找匹配的多个队列。
            3.  队列按照 `app.use` 注册时的顺序串行执行。
            4.  最后跟全局队列串行起来
    2. onUninstall: 不做隔离
    3. onFetch:  运行时，判断是哪个 client 发起的请求
        1. [x] [fetchEvent.clientId](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/clientId) 能用么？
            1. 当 fetchEvent 是 navigation fetch（即在浏览器直接输入地址），clientId 会为空
                1. 这时候就取资源的 url
                2. 是否还有更充分的判断条件来识别 navigation fetch
        2. [fetchEvent.resultingClientId](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/resultingClientId) 能用么？
            1. id 在 navigation 完成之后会变化
            2. 如果在 navigation fetch 执行 `await clients.get(resultingClientId)` 会阻塞，猜测应该是要等 onfetch 处理完之后才进行 resultingClientId 的初始化。所以做不到获取 url 去判断是否能阻断当前 onfetch
    4. onMessage：运行时，判断是哪个 client 过来的消息
        1. [x] ExtendableMessageEvent.source.url
    5. 处理方式：
        1. 只支持运行时事件支持 scope ：message & fetch
            1. 优点：对于 client 的判断很准确，就算client未被激活。
            2. 缺点：app.use(scope, middlewares)，并不像代码表现得那么确切。
        2. 支持全部事件隔离：（存在争议，后续再考虑是否加上）
            1. 优点：app.use(scope, middlewares), 就像代码表示的那样完全隔离。
            2. 思考：
                1. 是否有必要？
                    1. 有必要：保持与 window 侧的逻辑一样，实现全部逻辑的隔离
                2. 如果前一次安装，没有命中，后面修改代码，是否也能命中？
                    1. 会命中，修改代码会触发 sw 的注册和安装

**Comment by tangxiaojun1996** [comment]
> 

请问这个目前是支持了吗？我看源码里use还只是接受plugin的参数，并且这边的状态是open的 🤔

**Comment by JerryC8080** [comment]
@tangxiaojun1996  嗯，open 的状态，表示是正在开发的。

**Comment by tangxiaojun1996** [comment]
> 

好的。方便了解下实现思路吗？因为最近我们这边也有这个功能的需求场景，具体是在微前端项目中，在主框架注册的sw，期望只针对主框架自身、或部分子应用生效。我的想法是workbox registerRoute的matcher对路由做一个匹配？

**Comment by JerryC8080** [comment]
@tangxiaojun1996  

嗯，我觉得你简单的用workbox registerRoute对路由做匹配是可以实现的。但这种方式就像 if-else，对后面其他子应用要个性化使用 ServiceWroker 的功能会很困难。

这个隔离的实现在 GlacierJS 其实很简单，因为 GlacierJS 内部已经维护了一个「中间件队列（[MiddlewareQueue](https://github.com/JerryC8080/GlacierJS/blob/master/packages/core/src/lib/middleware-queue.ts)）」，那么我要做的其实是给每一个 `glacier.use(capture, pluginsLists)` 多建一个子 MiddlewareQueue 实例，由主 MiddlewareQueue 去按照当前受控的 Client 的路径来分流控制权到对应的子 MiddlewareQueue
